# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cce87980baaef8bbb0794922111a3da432da9c92aba3a3fe1c25aa2b7ab7489ec5427a2988b1d97013d0244e08c90b22e67e7b5c9b196e9ae01834dc74bd3de

test:
  secret_key_base: 09de92ae9b0b13d014b785f5158d7cce837a9434cbe6988023d1bcce5c5a57469871dc0f3f698e6aade55f2d11b17c9bbda6621b1e2d9c43b769e8b6a230559a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
